title: My Training Site
author: Lisa Vanderbilt-DeVol
email: vanderl3@nationwide.com
description: > # this means to ignore newlines until "baseurl:"
  This site is all about my venture into the world of GitHub
  and GitPages.

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
